GB_Project_Settings = {
    name = "ALL",
    w = 640,
    h = 420,
    x = 0,
    y = 0,
    anchor = "mouse",
    corner = "C",
}

GB_Project_Elements_Names = {
    "dh_Listbox1",
    "dh_Menubar1",
    "dh_Knob1",
    "dh_Menubox1",
    "dh_TextEditor1",
    "dh_Button1",
    "dh_Slider_H1",
    "dh_Textbox1",
    "dh_Label1",
    "dh_Checklist1",
    "dh_Tabs1",
}

GUI.New("dh_Listbox1", "dh_Listbox", {
    z = 11,
    x = 320,
    y = 96,
    w = 156,
    h = 96,
    list = {
        "Item 1",
        "Item 2",
        "Item 3",
        "Item 4",
    },
    multi = false,
    scrollbar_width = 8,
    font_text = "sans22",
    pad = 4,
    line_height = 1.2,
    caption = "dh_Listbox1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    shadow = false,
    col_bg = "elm_bg",
    frame_use_outline = false,
    frame_thk = "2",
    col_frame = "elm_frame",
    col_text = "elm_txt",
    col_track = "btn_face",
    col_thumb = "btn_outline",
    col_cap_text = "txt",
    col_sel_text = "sel_txt",
    use_sel_alpha = false,
    sel_alpha = 0.5,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
})

GUI.New("dh_Menubar1", "dh_Menubar", {
    z = 11,
    x = 0,
    y = 0,
    w = 960,
    h = 28,
    fullwidth = true,
    limit_w = 0,
    font = "sans22",
    menus = {
        {title = "Menu 1", options = {}},
        {title = "Menu 2", options = {}},
        {title = "Menu 3", options = {}},
    },
    shadow = true,
    col_bg = "btn_face",
    col_text = "btn_txt",
    col_over = "elm_fill",
    do_pad_top = false,
    pad_top_val = 0,
})

GUI.New("dh_Knob1", "dh_Knob", {
    z = 11,
    x = 240,
    y = 160,
    w = 40,
    centered = true,
    knob_style = "simple",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = false,
    caption = "dh_Knob1",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad = 16,
    shadow_caption = false,
    show_values = false,
    font_values = "sans18",
    pad_values = 4,
    output = nil,
    col_bg = "wnd_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_indicator = "btn_txt",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {10,"10"},
    },
    display_style = "box",
    display_w = 48,
    display_h = 26,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Menubox1", "dh_Menubox", {
    z = 11,
    x = 496,
    y = 96,
    w = 128,
    h = 28,
    noarrow = false,
    optarray = {"Option 1", "Option 2" , "Option 3", "Option 4"},
    curr_opt = 1,
    font_text = "sans22",
    pad = 4,
    align_text = "left",
    caption = "dh_Menubox1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    shadow = false,
    col_bg = "elm_bg",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
    col_face = "btn_face",
    col_text = "elm_txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
})

GUI.New("dh_TextEditor1", "dh_TextEditor", {
    z = 11,
    x = 336,
    y = 240,
    w = 256,
    h = 156,
    font_text = "mono16",
    pad = 4,
    line_height = 1.4,
    undo_limit = 20,
    scrollbar_width = 8,
    caption = "dh_TextEditor1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    shadow = false,
    col_bg = "elm_bg",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
    col_text = "elm_txt",
    col_cap_text = "txt",
    col_track = "btn_face",
    col_thumb = "btn_outline",
    col_sel_text = "sel_txt",
    use_sel_alpha = false,
    sel_alpha = 0.5,
    allow_sel_outline = true,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    retval = {
        "This is some text.",
        "This is more text.",
        "This is some text.",
        "This is more text.",
        "This is some text.",
        "This is more text.",
        "This is some text.",
        "This is more text",
    },
})

GUI.New("dh_Button1", "dh_Button", {
    z = 11,
    x = 48,
    y = 256,
    w = 64,
    h = 28,
    text = "Button",
    font = "sans22",
    shadow = nil,
    shadow_text = false,
    col_bg = "btn_face",
    col_outline = "btn_outline",
    col_text = "btn_txt",
    col_active = "elm_active",
    allow_sel_outline = false,
})

GUI.New("dh_Slider_H1", "dh_Slider_H", {
    z = 11,
    x = 32,
    y = 320,
    w = 256,
    h = 68,
    track_thk = 8,
    thumb_style = "long",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_H1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    border_width = 2,
    radius = 4,
    shadow = false,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = false,
    default_tickmarks = {5, },
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = -4,
    tickmarks_offset = 2,
    display_style = "box",
    display_w = 48,
    display_h = 26,
    display_pos = "integrated",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})

GUI.New("dh_Textbox1", "dh_Textbox", {
    z = 11,
    x = 496,
    y = 160,
    w = 96,
    h = 28,
    font_text = "mono16",
    pad = 4,
    align_text = "left",
    pad = 4,
    undo_limit = 20,
    caption = "dh_Textbox1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    shadow = false,
    col_bg = "elm_bg",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
    col_text = "elm_txt",
    col_cap_text = "txt",
    col_sel_text = "sel_txt",
    use_sel_alpha = false,
    sel_alpha = 0.5,
    allow_sel_outline = true,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    retval = "hello",
})

GUI.New("dh_Label1", "dh_Label", {
    z = 11,
    x = 176,
    y = 256,
    text = "Label",
    font = "sans22",
    text_pos = "left",
    col_bg = "wnd_bg",
    col_text = "txt",
    shadow_text = false,
})

GUI.New("dh_Checklist1", "dh_Checklist", {
    z = 11,
    x = 32,
    y = 96,
    w = 128,
    h = 128,
    dir = "v",
    optarray = {
        "Option 1",
        "Option 2",
        "Option 3",
        "Option 4",
    },
    opt_size = 14,
    swap = false,
    border_width = 2,
    radius = 8,
    caption = "dh_Checklist1",
    font_caption = "sans22",
    cap_pos = "inside",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    font_text = "sans22",
    pad_x = 10,
    pad_y = 8,
    shadow_text = false,
    shadow = false,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_text = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
})

GUI.New("dh_Tabs1", "dh_Tabs", {
    z = 11,
    x = 0,
    y = 28,
    fullwidth = true,
    limit_w = 0,
    optarray = {
        "Tab 1",
        "Tab 2",
        "Tab 3",
    },
    tab_w = 48,
    tab_h = 26,
    pad = 8,
    font_tab_active = "sans24",
    font_tab_inactive = "sans22",
    col_bg = "elm_bg",
    col_text = "btn_txt",
    col_tab_active = "tab_active",
    col_tab_inactive = "tab_inactive",
})



