-- # GUI Builder Project file v1

GB_Project_Settings = {
    name = "KNOBS",
    w = 640,
    h = 420,
    x = 0,
    y = 0,
    anchor = "mouse",
    corner = "C",
}

GB_Project_Elements_Names = {
    "dh_Knob1",
    "dh_Knob5",
    "dh_Knob8",
    "dh_Panel1",
    "dh_Knob2",
    "dh_Knob7",
    "dh_Knob4",
    "dh_Knob6",
    "dh_Knob3",
}
GUI.New("dh_Knob1", "dh_Knob", {
    z = 11,
    x = 96,
    y = 144,
    w = 60,
    centered = true,
    knob_style = "pointer",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = false,
    caption = "dh_Knob1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad = 20,
    shadow_caption = false,
    show_values = true,
    font_values = "sans20",
    pad_values = 10,
    col_bg = "wnd_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    display_style = "none",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans20",
    display_align = 0,
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob5", "dh_Knob", {
    z = 11,
    x = 320,
    y = 320,
    w = 60,
    centered = true,
    knob_style = "flange",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = false,
    caption = "dh_Knob5",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad = -4,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "panel_bg",
    col_outline = "elm_outline",
    col_body = "elm_bg",
    col_values = "panel_txt",
    col_cap_text = "panel_txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    display_style = "box",
    display_w = 48,
    display_h = 24,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 12,
    font_display = "sans22",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob8", "dh_Knob", {
    z = 11,
    x = 208,
    y = 80,
    w = 40,
    centered = true,
    knob_style = "pointer",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = true,
    caption = "dh_Knob8",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad = 4,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "wnd_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 6,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    display_style = "none",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans20",
    display_align = 0,
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob2", "dh_Knob", {
    z = 11,
    x = 320,
    y = 144,
    w = 60,
    centered = true,
    knob_style = "flange",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = false,
    caption = "dh_Knob2",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad = 4,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 8,
    col_bg = "wnd_bg",
    col_outline = "elm_outline",
    col_body = "elm_bg",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    display_style = "plain",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 16,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob7", "dh_Knob", {
    z = 11,
    x = 432,
    y = 80,
    w = 40,
    centered = true,
    knob_style = "simple",
    min = 0,
    max = 6,
    default = 3,
    inc = 1,
    shadow = false,
    caption = "dh_Knob7",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad = 4,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "wnd_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 6,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 2, 4, 6, },
    hard_tick_size = 6,
    hard_tick_thk = true,
    show_min_max = true,
    min_max_values = {
        {0,"Low"},
        {6,"High"},
    },
    display_style = "none",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans20",
    display_align = 0,
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob4", "dh_Knob", {
    z = 11,
    x = 128,
    y = 320,
    w = 60,
    centered = true,
    knob_style = "pointer",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = true,
    caption = "dh_Knob4",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad = 8,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "panel_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "panel_txt",
    col_cap_text = "panel_txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 6,
    hard_tick_thk = false,
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {10,"10"},
    },
    display_style = "none",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans20",
    display_align = 0,
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob6", "dh_Knob", {
    z = 11,
    x = 512,
    y = 320,
    w = 60,
    centered = true,
    knob_style = "simple",
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    shadow = true,
    caption = "dh_Knob6",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad = 4,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "panel_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "panel_txt",
    col_cap_text = "panel_txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 8,
    hard_tick_thk = true,
    show_min_max = true,
    min_max_values = {
        {0,"0 "},
        {5,"5"},
        {10,"10"},
    },
    display_style = "none",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 8,
    font_display = "sans20",
    display_align = 0,
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})

GUI.New("dh_Knob3", "dh_Knob", {
    z = 11,
    x = 544,
    y = 144,
    w = 60,
    centered = true,
    knob_style = "simple",
    min = 0,
    max = 100,
    default = 50,
    inc = 1,
    shadow = false,
    caption = "dh_Knob3",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad = 8,
    shadow_caption = false,
    show_values = false,
    font_values = "sans20",
    pad_values = 4,
    col_bg = "wnd_bg",
    col_outline = "btn_outline",
    col_body = "btn_face",
    col_values = "txt",
    col_cap_text = "txt",
    allow_sel_outline = false,
    col_active = "elm_active",
    show_tickmarks = true,
    tickmark_steps = 10,
    tickmark_size = 4,
    pad_ticks = 4,
    hard_ticks = {0, 5, 10, },
    hard_tick_size = 8,
    hard_tick_thk = true,
    show_min_max = true,
    min_max_values = {
        {0,"0 "},
        {100,"100"},
    },
    display_style = "box",
    display_w = 48,
    display_h = 28,
    display_pos = "top",
    display_pad_x = 0,
    display_pad_y = 12,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
    frame_use_outline = false,
    frame_thk = 2,
    col_frame = "elm_frame",
})




GUI.New("dh_Panel1", "dh_Panel", {
    z = 21,
    x = 32,
    y = 230,
    w = 572,
    h = 178,
    border_width = 4,
    radius = 4,
    shadow = false,
    caption = "",
    font_caption = "sans22",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    text = nil,
    font_text = "mono16",
    pad = 4,
    line_height = 1.25,
    use_pixels = false,
    line_height_pixels = 24,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_text = "panel_txt",
    col_cap_text = "txt",
    col_backdrop = "wnd_bg",
})



