GB_Project_Settings = {
    name = "SLIDERS",
    w = 640,
    h = 420,
    x = 0,
    y = 0,
    anchor = "mouse",
    corner = "C",
}

GB_Project_Elements_Names = {
    "dh_Slider_H1",
    "dh_Slider_H2",
    "dh_Slider_H4",
    "dh_Slider_H3",
    "dh_Slider_V2",
    "dh_Slider_V1",
}

GUI.New("dh_Slider_H1", "dh_Slider_H", {
    z = 11,
    x = 80,
    y = 48,
    w = 212,
    h = 32,
    track_thk = 8,
    thumb_style = "wide",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_H1",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    border_width = 0,
    radius = 8,
    shadow = false,
    col_bg = "wnd_bg",
    col_border = "btn_outline",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = false,
    default_tickmarks = {5, },
    show_min_max = false,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = 0,
    tickmarks_offset = 2,
    display_style = "plain",
    display_w = 48,
    display_h = 20,
    display_pos = "top",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "txt",
})

GUI.New("dh_Slider_H2", "dh_Slider_H", {
    z = 11,
    x = 80,
    y = 144,
    w = 212,
    h = 36,
    track_thk = 8,
    thumb_style = "long",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_H2",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    border_width = 2,
    radius = 4,
    shadow = true,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = false,
    tickmark_steps = 10,
    show_default_tickmarks = true,
    default_tickmarks = {5, },
    show_min_max = true,
    min_max_values = {
        {0,"Min"},
        {10,"Max"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = 0,
    tickmarks_offset = 0,
    display_style = "box",
    display_w = 48,
    display_h = 28,
    display_pos = "top",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})

GUI.New("dh_Slider_H4", "dh_Slider_H", {
    z = 11,
    x = 64,
    y = 224,
    w = 256,
    h = 72,
    track_thk = 8,
    thumb_style = "long",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_H4",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    border_width = 2,
    radius = 4,
    shadow = true,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = true,
    default_tickmarks = {5, },
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {10,"10"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = -2,
    tickmarks_offset = 2,
    display_style = "box",
    display_w = 48,
    display_h = 24,
    display_pos = "integrated",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "right",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})

GUI.New("dh_Slider_H3", "dh_Slider_H", {
    z = 11,
    x = 64,
    y = 352,
    w = 256,
    h = 32,
    track_thk = 8,
    thumb_style = "long",
    fill_from_default = false,
    min = 0,
    max = 100,
    default = 50,
    inc = 1,
    caption = "dh_Slider_H3",
    font_caption = "sans22",
    cap_pos = "top",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = false,
    shadow_caption = false,
    border_width = 1,
    radius = 4,
    shadow = true,
    col_bg = "wnd_bg",
    col_border = "btn_outline",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = true,
    default_tickmarks = {50, },
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {50,"50"},
        {100,"100"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = 0,
    tickmarks_offset = 2,
    display_style = "box",
    display_w = 48,
    display_h = 24,
    display_pos = "right",
    display_pad_x = 8,
    display_pad_y = 0,
    font_display = "sans22",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})

GUI.New("dh_Slider_V2", "dh_Slider_V", {
    z = 11,
    x = 400,
    y = 64,
    w = 36,
    h = 220,
    track_thk = 8,
    thumb_style = "wide",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_V2",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = true,
    shadow_caption = false,
    border_width = 2,
    radius = 8,
    shadow = true,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = true,
    default_tickmarks = {5, },
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    show_values = false,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = 0,
    tickmarks_offset = -2,
    display_style = "box",
    display_w = 36,
    display_h = 24,
    display_pos = "top",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})

GUI.New("dh_Slider_V1", "dh_Slider_V", {
    z = 11,
    x = 512,
    y = 64,
    w = 48,
    h = 220,
    track_thk = 8,
    thumb_style = "long",
    fill_from_default = false,
    min = 0,
    max = 10,
    default = 5,
    inc = 1,
    caption = "dh_Slider_V1",
    font_caption = "sans22",
    cap_pos = "bottom",
    cap_pad_x = 4,
    cap_pad_y = 4,
    cap_centered = true,
    shadow_caption = false,
    border_width = 2,
    radius = 8,
    shadow = true,
    col_bg = "panel_bg",
    col_border = "panel_border",
    col_values = "txt",
    col_cap_text = "txt",
    col_track = "elm_bg",
    col_frame = "elm_frame",
    col_thumb = "btn_face",
    col_thumb_outline = "btn_outline",
    col_fill = "track_fill",
    frame_use_outline = false,
    frame_thk = 2,
    allow_sel_outline = false,
    col_active = "elm_active",
    col_backdrop = "wnd_bg",
    show_tickmarks = true,
    tickmark_steps = 10,
    show_default_tickmarks = true,
    default_tickmarks = {5, },
    show_min_max = true,
    min_max_values = {
        {0,"0"},
        {5,"5"},
        {10,"10"},
    },
    show_values = true,
    font_values = "sans18",
    output = nil,
    pad_values = 4,
    track_offset = -4,
    tickmarks_offset = 4,
    display_style = "box",
    display_w = 36,
    display_h = 24,
    display_pos = "top",
    display_pad_x = 8,
    display_pad_y = 8,
    font_display = "sans24",
    display_align = "center",
    col_display_bg = "elm_bg",
    col_display_text = "elm_txt",
})



